"""add tenant column comments

Revision ID: 0e1b73d98cb3
Revises: 3c2b8f88b1a5
Create Date: 2025-11-29 21:11:23.222690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e1b73d98cb3'
down_revision: Union[str, None] = '3c2b8f88b1a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_members', 'user_id',
               existing_type=sa.UUID(),
               comment='Identifier of the linked user account',
               existing_nullable=False)
    op.alter_column('tenant_members', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Owning tenant identifier',
               existing_nullable=False)
    op.alter_column('tenant_members', 'id',
               existing_type=sa.UUID(),
               comment='Primary key generated via PostgreSQL uuidv7()',
               existing_nullable=False,
               existing_server_default=sa.text('uuidv7()'))
    op.alter_column('tenant_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_members', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_members', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was soft deleted',
               existing_nullable=True)
    op.alter_column('tenant_members', 'deleted_by',
               existing_type=sa.UUID(),
               comment='Identifier of the principal that soft deleted the record',
               existing_nullable=True)
    op.alter_column('tenant_members', 'created_by',
               existing_type=sa.UUID(),
               comment='Identifier of the principal that created the record',
               existing_nullable=True)
    op.alter_column('tenant_members', 'updated_by',
               existing_type=sa.UUID(),
               comment='Identifier of the principal that last updated the record',
               existing_nullable=True)
    op.alter_column('tenant_members', 'version',
               existing_type=sa.INTEGER(),
               comment='Optimistic concurrency control counter',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('tenants', 'id',
               existing_type=sa.UUID(),
               comment='Primary key generated via PostgreSQL uuidv7()',
               existing_nullable=False,
               existing_server_default=sa.text('uuidv7()'))
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was soft deleted',
               existing_nullable=True)
    op.alter_column('tenants', 'deleted_by',
               existing_type=sa.UUID(),
               comment='Identifier of the principal that soft deleted the record',
               existing_nullable=True)
    op.alter_column('tenants', 'created_by',
               existing_type=sa.UUID(),
               comment='Identifier of the principal that created the record',
               existing_nullable=True)
    op.alter_column('tenants', 'updated_by',
               existing_type=sa.UUID(),
               comment='Identifier of the principal that last updated the record',
               existing_nullable=True)
    op.alter_column('tenants', 'version',
               existing_type=sa.INTEGER(),
               comment='Optimistic concurrency control counter',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Optimistic concurrency control counter',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('tenants', 'updated_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identifier of the principal that last updated the record',
               existing_nullable=True)
    op.alter_column('tenants', 'created_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identifier of the principal that created the record',
               existing_nullable=True)
    op.alter_column('tenants', 'deleted_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identifier of the principal that soft deleted the record',
               existing_nullable=True)
    op.alter_column('tenants', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was soft deleted',
               existing_nullable=True)
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key generated via PostgreSQL uuidv7()',
               existing_nullable=False,
               existing_server_default=sa.text('uuidv7()'))
    op.alter_column('tenant_members', 'version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Optimistic concurrency control counter',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('tenant_members', 'updated_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identifier of the principal that last updated the record',
               existing_nullable=True)
    op.alter_column('tenant_members', 'created_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identifier of the principal that created the record',
               existing_nullable=True)
    op.alter_column('tenant_members', 'deleted_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identifier of the principal that soft deleted the record',
               existing_nullable=True)
    op.alter_column('tenant_members', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was soft deleted',
               existing_nullable=True)
    op.alter_column('tenant_members', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_members', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key generated via PostgreSQL uuidv7()',
               existing_nullable=False,
               existing_server_default=sa.text('uuidv7()'))
    op.alter_column('tenant_members', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Owning tenant identifier',
               existing_nullable=False)
    op.alter_column('tenant_members', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identifier of the linked user account',
               existing_nullable=False)
    # ### end Alembic commands ###