"""initial: setup PostgreSQL 18 with uuidv7 support

Revision ID: 9814f556d003
Revises: 
Create Date: 2025-10-02 13:41:01.132591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9814f556d003'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Verify PostgreSQL 18+ with uuidv7() support
    op.execute("""
        DO $$
        DECLARE
            pg_version INTEGER;
        BEGIN
            SELECT current_setting('server_version_num')::INTEGER INTO pg_version;

            IF pg_version < 180000 THEN
                RAISE EXCEPTION 'PostgreSQL 18+ is required for uuidv7() support. Current version: %',
                    current_setting('server_version');
            END IF;

            -- Test uuidv7() function availability
            PERFORM uuidv7();
        END $$;
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###