name: Backend Quality Check

on:
  push:
    branches: [main]
    paths: ['api/**']
  pull_request:
    branches: [main]
    paths: ['api/**']

jobs:
  quality-check:
    name: Backend Quality
    uses: ./.github/workflows/_reusable-quality-backend.yml
    secrets: inherit
