name: Frontend Quality Check

on:
  push:
    branches: [main]
    paths: ['web/**']
  pull_request:
    branches: [main]
    paths: ['web/**']

jobs:
  quality-check:
    name: Frontend Quality
    uses: ./.github/workflows/_reusable-quality-frontend.yml
    secrets: inherit